name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger ONLY on final version tags (e.g., v0.1.0, v1.2.3) - no suffixes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build and twine
        run: pip install build twine

      - name: Build package
        run: python -m build

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}