name: Publish Python Package to PyPI using Trusted Publishing

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger ONLY on final version tags (e.g., v0.1.0, v1.2.3) - no suffixes

jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use a more recent version

      - name: Set up Python
        uses: actions/setup-python@v5 # Use a more recent version
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1